export const SET_APP_LOADING = 'SET_APP_LOADING';
export const USER_LOGOUT = 'USER_LOGOUT';

export const BOOKMARKED_JOBS = 'BOOKMARKED_JOBS';
export const TOGGLE_BOOKMARKED_JOB = 'TOGGLE_BOOKMARKED_JOB';

export const ALL_JOBS = 'ALL_JOBS';
export const ALL_JOBS_SUCCESS = 'ALL_JOBS_SUCCESS';
export const ALL_JOBS_FAILURE = 'ALL_JOBS_FAILURE';
